SELECT
	ai.ANIMAL_ID,
	ai.ANIMAL_TYPE,
	ai.NAME
FROM
	ANIMAL_INS AS ai
INNER JOIN
	ANIMAL_OUTS AS ao
ON 1 = 1
	AND ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE 1 = 1
	AND ai.SEX_UPON_INTAKE LIKE 'Intact%'
	AND (
		ao.SEX_UPON_OUTCOME LIKE 'Spayed%'
		OR ao.SEX_UPON_OUTCOME LIKE 'Neutered%'
	)
ORDER BY
	ai.ANIMAL_ID
;