SELECT
    fp.PRODUCT_ID,
    fp.PRODUCT_NAME,
    SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS fp
INNER JOIN FOOD_ORDER AS fo
ON 1 = 1
    AND fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE 1 = 1
    AND DATE_FORMAT(fo.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY
    fp.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    fp.PRODUCT_ID ASC
;