SELECT
    p.PRODUCT_CODE,
    COALESCE(SUM(p.PRICE * os.SALES_AMOUNT), 0) AS SALES
FROM
    PRODUCT AS p
LEFT JOIN
    OFFLINE_SALE AS os
ON 1 = 1
AND p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY
    p.PRODUCT_CODE
ORDER BY
    SALES DESC,
    p.PRODUCT_CODE ASC
;