SELECT
    p.PRODUCT_CODE,
    SUM(p.PRICE * os.SALES_AMOUNT) AS SALES
FROM
    PRODUCT AS p
INNER JOIN
    OFFLINE_SALE AS os
ON 1 = 1
AND p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY
    p.PRODUCT_CODE
ORDER BY
    SALES DESC,
    p.PRODUCT_CODE ASC
;