SELECT
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    info.GENDER AS GENDER,
    COUNT(DISTINCT info.USER_ID) AS USERS
FROM
    USER_INFO AS info
RIGHT JOIN ONLINE_SALE AS os
ON 1 = 1
    AND info.USER_ID = os.USER_ID
WHERE info.GENDER IS NOT NULL
GROUP BY
    YEAR(os.SALES_DATE),
    MONTH(os.SALES_DATE),
    info.GENDER
ORDER BY
    YEAR ASC,
    MONTH ASC,
    GENDER ASC
;
    