WITH FP2 AS (
SELECT
    CATEGORY,
    MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE 1 = 1
AND CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
)

SELECT
    FP1.CATEGORY,
    FP1.PRICE,
    FP1.PRODUCT_NAME
FROM
    FOOD_PRODUCT AS FP1,
    FP2
WHERE 1 = 1
AND FP1.CATEGORY = FP2.CATEGORY
AND FP1.PRICE = FP2.MAX_PRICE
;