SELECT
    ugb.WRITER_ID,
    ugu.NICKNAME,
    SUM(ugb.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS ugb
INNER JOIN USED_GOODS_USER AS ugu
ON 1 = 1
    AND ugb.WRITER_ID = ugu.USER_ID
WHERE 1 =1
    AND ugb.STATUS = 'DONE'
GROUP BY ugb.WRITER_ID
HAVING 1 = 1
    AND SUM(ugb.PRICE) >= 700000
ORDER BY
    TOTAL_SALES ASC
;