SELECT
    DISTINCT c.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
INNER JOIN
    CAR_RENTAL_COMPANY_CAR AS c
ON 1 = 1
    AND h.CAR_ID = c.CAR_ID
WHERE 1 = 1
    AND c.CAR_TYPE = '세단'
    AND MONTH(h.START_DATE) = 10
ORDER BY
    c.CAR_ID DESC
;