WITH ft AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 1 = 1
        AND YEAR(START_DATE) = 2022
        AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY
        CAR_ID
    HAVING 1 = 1
        AND COUNT(*) >= 5
)


SELECT
    MONTH(h.START_DATE) AS MONTH,
    h.CAR_ID,
    COUNT(h.HISTORY_ID) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h,
    ft
WHERE 1 = 1
    AND YEAR(START_DATE) = 2022
    AND MONTH(START_DATE) BETWEEN 8 AND 10
    AND h.CAR_ID IN (ft.CAR_ID)
GROUP BY
    MONTH(h.START_DATE),
    h.CAR_ID
HAVING 1 = 1
    AND COUNT(h.HISTORY_ID) > 0
ORDER BY
    MONTH ASC,
    h.CAR_ID DESC
;