WITH up3 AS (
    SELECT
        WRITER_ID
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING COUNT(*) >= 3
)

SELECT
    USER_ID,
    NICKNAME,
    CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS('-', SUBSTR(TLNO, 1, 3), SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM
    USED_GOODS_USER, up3
WHERE 1 = 1
    AND USER_ID IN (up3.WRITER_ID)
ORDER BY USER_ID DESC
;