WITH u AS (
    SELECT
        USER_ID,
        COUNT(*) OVER() AS TOTAL_CNT
    FROM
        USER_INFO
    WHERE 1 = 1
        AND YEAR(JOINED) = 2021
)


SELECT
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT u.USER_ID) / u.TOTAL_CNT, 1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE AS os
INNER JOIN u
ON 1 = 1
    AND u.USER_ID = os.USER_ID
GROUP BY
    YEAR(os.SALES_DATE),
    MONTH(os.SALES_DATE)
ORDER BY
    YEAR ASC,
    MONTH ASC
;